### ISSUE TITLE
Install Vuetify

### ISSUE THREAD

**Issue by MarcoTribuz** [Realise-Formation-Digital/vue-music-project-1#2]
- Dans le dossier root de votre projet (là où se situe votre fichier package.json, tapez:
`npm install vuetify`

- Dans votre fichier main.js, ajouter les 3 lignes suivantes:

```
import Vuetify from 'vuetify';
import 'vuetify/dist/vuetify.min.css';
Vue.use(Vuetify);
```

**Comment by ashkam1201** [comment]
done
