### ISSUE TITLE
Install Axios or Node-fetch

### ISSUE THREAD

**Issue by MarcoTribuz** [Realise-Formation-Digital/vue-music-project-1#3]
Vous avez le choix de ce que vous voulez installer, axios ou node-fetch.

Voici comment installer les deux bibliothèques

`npm install axios
`

ou

`npm install node-fetch
`
### 
**_VEUILLEZ NOTER ! Un seul des deux, pas les deux_**

**Comment by ashkam1201** [comment]
done
